In [57]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
import numpy as np

In [58]:
df = pd.read_csv("student.csv")
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
2,64003,NaN,NaN,Male,Science,3.67,175.0,NaN,25.0,2024-01-13
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-02-11
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03
10,64011,ธีระ,NaN,NaN,NaN,3.78,NaN,68.0,NaN,2024-01-07
11,64012,นภา,22.0,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-26
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24
17,64018,ยุพา,21.0,หญิง,NaN,3.23,161.0,50.0,27.0,2024-01-08
18,64019,รัตนา,NaN,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18
19,64020,ลัดดา,22.0,NaN,Science,3.45,168.0,64.0,23.0,2024-01-06

In [59]:
new_data = df.copy()

In [60]:
new_data['ชื่อ'] = new_data['ชื่อ'].fillna('ไม่ระบุ')
new_data

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
2,64003,ไม่ระบุ,NaN,Male,Science,3.67,175.0,NaN,25.0,2024-01-13
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-02-11
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03
10,64011,ธีระ,NaN,NaN,NaN,3.78,NaN,68.0,NaN,2024-01-07
11,64012,นภา,22.0,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-26
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24
17,64018,ยุพา,21.0,หญิง,NaN,3.23,161.0,50.0,27.0,2024-01-08
18,64019,รัตนา,NaN,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18
19,64020,ลัดดา,22.0,NaN,Science,3.45,168.0,64.0,23.0,2024-01-06

In [61]:
def standardize_gender(เพศ):
    if เพศ in ['หญิง', 'Female', 'F', 'ญ']:
        return 'หญิง'
    elif เพศ in ['ชาย', 'ช', 'Male', 'M']:
        return 'ชาย'
    else:
        return เพศ

new_data['เพศ'] = new_data['เพศ'].apply(standardize_gender)
new_data

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
2,64003,ไม่ระบุ,NaN,ชาย,Science,3.67,175.0,NaN,25.0,2024-01-13
3,64004,สมศักดิ์,22.0,ชาย,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.0,หญิง,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05
7,64008,จิรา,20.0,หญิง,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23
8,64009,ชนาธิป,23.0,ชาย,Arts,3.34,163.0,55.0,22.0,2024-02-11
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03
10,64011,ธีระ,NaN,NaN,NaN,3.78,NaN,68.0,NaN,2024-01-07
11,64012,นภา,22.0,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-26
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08
14,64015,พิมพ์,22.0,หญิง,Sci,3.67,162.0,56.0,26.0,2024-02-06
15,64016,ภูมิ,19.0,ชาย,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20
16,64017,มานี,20.0,หญิง,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24
17,64018,ยุพา,21.0,หญิง,NaN,3.23,161.0,50.0,27.0,2024-01-08
18,64019,รัตนา,NaN,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18
19,64020,ลัดดา,22.0,NaN,Science,3.45,168.0,64.0,23.0,2024-01-06

In [62]:
def standardize_faculty(คณะ):
    if คณะ in ['วิทยาศาสตร์', 'วิทย์', 'คณะวิทยาศาสตร์', 'Science', 'Sci']:
        return 'วิทยาศาสตร์'
    elif คณะ in ['วิศวะ', 'Engineering', 'วิศวกรรม', 'วิศวฯ', 'วิศวกรรมศาสตร์']:
        return 'วิศวกรรมศาสตร์'
    elif คณะ in ['ศิลปศาสตร์', 'Arts', 'ศิลป์', 'Liberal Arts']:
        return 'ศิลปศาสตร์'
    else:
        return คณะ

new_data['คณะ'] = new_data['คณะ'].apply(standardize_faculty)
new_data

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.0,หญิง,วิทยาศาสตร์,3.45,165.0,58.0,20.0,2024-02-05
2,64003,ไม่ระบุ,NaN,ชาย,วิทยาศาสตร์,3.67,175.0,NaN,25.0,2024-01-13
3,64004,สมศักดิ์,22.0,ชาย,วิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.0,หญิง,วิศวกรรมศาสตร์,3.89,160.0,52.0,30.0,2024-01-27
5,64006,กานต์,150.0,ชาย,วิศวกรรมศาสตร์,3.12,172.0,75.0,12.0,2023-12-23
6,64007,กิตติ,21.0,หญิง,วิศวกรรมศาสตร์,4.50,158.0,48.0,35.0,2024-01-05
7,64008,จิรา,20.0,หญิง,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23
8,64009,ชนาธิป,23.0,ชาย,ศิลปศาสตร์,3.34,163.0,55.0,22.0,2024-02-11
9,64010,ดารา,21.0,หญิง,ศิลปศาสตร์,3.56,167.0,60.0,28.0,2024-01-03
10,64011,ธีระ,NaN,NaN,NaN,3.78,NaN,68.0,NaN,2024-01-07
11,64012,นภา,22.0,ชาย,วิทยาศาสตร์,NaN,171.0,NaN,16.0,2023-12-26
12,64013,บุญมี,20.0,หญิง,วิศวกรรมศาสตร์,3.23,169.0,72.0,24.0,2023-12-26
13,64014,ปรีชา,21.0,ชาย,ศิลปศาสตร์,3.45,164.0,54.0,19.0,2024-01-08
14,64015,พิมพ์,22.0,หญิง,วิทยาศาสตร์,3.67,162.0,56.0,26.0,2024-02-06
15,64016,ภูมิ,19.0,ชาย,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20
16,64017,มานี,20.0,หญิง,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24
17,64018,ยุพา,21.0,หญิง,NaN,3.23,161.0,50.0,27.0,2024-01-08
18,64019,รัตนา,NaN,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18
19,64020,ลัดดา,22.0,NaN,วิทยาศาสตร์,3.45,168.0,64.0,23.0,2024-01-06

In [63]:
mean_gpa = new_data['GPA'].mean()
new_data.loc[new_data['GPA'] < 0, 'GPA'] = np.nan
new_data.loc[new_data['GPA'] > 4, 'GPA'] = 4.0
new_data['GPA'].fillna(mean_gpa, inplace=True)
new_data

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.210000,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.0,หญิง,วิทยาศาสตร์,3.450000,165.0,58.0,20.0,2024-02-05
2,64003,ไม่ระบุ,NaN,ชาย,วิทยาศาสตร์,3.670000,175.0,NaN,25.0,2024-01-13
3,64004,สมศักดิ์,22.0,ชาย,วิทยาศาสตร์,3.246111,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.0,หญิง,วิศวกรรมศาสตร์,3.890000,160.0,52.0,30.0,2024-01-27
5,64006,กานต์,150.0,ชาย,วิศวกรรมศาสตร์,3.120000,172.0,75.0,12.0,2023-12-23
6,64007,กิตติ,21.0,หญิง,วิศวกรรมศาสตร์,4.000000,158.0,48.0,35.0,2024-01-05
7,64008,จิรา,20.0,หญิง,ศิลปศาสตร์,2.980000,180.0,82.0,18.0,2024-01-23
8,64009,ชนาธิป,23.0,ชาย,ศิลปศาสตร์,3.340000,163.0,55.0,22.0,2024-02-11
9,64010,ดารา,21.0,หญิง,ศิลปศาสตร์,3.560000,167.0,60.0,28.0,2024-01-03
10,64011,ธีระ,NaN,NaN,NaN,3.780000,NaN,68.0,NaN,2024-01-07
11,64012,นภา,22.0,ชาย,วิทยาศาสตร์,3.246111,171.0,NaN,16.0,2023-12-26
12,64013,บุญมี,20.0,หญิง,วิศวกรรมศาสตร์,3.230000,169.0,72.0,24.0,2023-12-26
13,64014,ปรีชา,21.0,ชาย,ศิลปศาสตร์,3.450000,164.0,54.0,19.0,2024-01-08
14,64015,พิมพ์,22.0,หญิง,วิทยาศาสตร์,3.670000,162.0,56.0,26.0,2024-02-06
15,64016,ภูมิ,19.0,ชาย,วิทยาศาสตร์,3.890000,173.0,78.0,14.0,2024-01-20
16,64017,มานี,20.0,หญิง,วิศวกรรมศาสตร์,3.010000,166.0,62.0,21.0,2024-01-24
17,64018,ยุพา,21.0,หญิง,NaN,3.230000,161.0,50.0,27.0,2024-01-08
18,64019,รัตนา,NaN,ชาย,ศิลปศาสตร์,3.246111,174.0,76.0,NaN,2023-12-18
19,64020,ลัดดา,22.0,NaN,วิทยาศาสตร์,3.450000,168.0,64.0,23.0,2024-01-06

In [64]:
mean_19_23 = new_data.loc[(new_data['อายุ'] >= 19) & (new_data['อายุ'] <= 23), 'อายุ'].mean()
condition = (new_data['อายุ'] > 23) | (new_data['อายุ'].isna()) | (new_data['อายุ'] == "")
new_data.loc[condition, 'อายุ'] = mean_19_23
new_data

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.000,ชาย,วิทยาศาสตร์,3.210000,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.000,หญิง,วิทยาศาสตร์,3.450000,165.0,58.0,20.0,2024-02-05
2,64003,ไม่ระบุ,20.875,ชาย,วิทยาศาสตร์,3.670000,175.0,NaN,25.0,2024-01-13
3,64004,สมศักดิ์,22.000,ชาย,วิทยาศาสตร์,3.246111,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.000,หญิง,วิศวกรรมศาสตร์,3.890000,160.0,52.0,30.0,2024-01-27
5,64006,กานต์,20.875,ชาย,วิศวกรรมศาสตร์,3.120000,172.0,75.0,12.0,2023-12-23
6,64007,กิตติ,21.000,หญิง,วิศวกรรมศาสตร์,4.000000,158.0,48.0,35.0,2024-01-05
7,64008,จิรา,20.000,หญิง,ศิลปศาสตร์,2.980000,180.0,82.0,18.0,2024-01-23
8,64009,ชนาธิป,23.000,ชาย,ศิลปศาสตร์,3.340000,163.0,55.0,22.0,2024-02-11
9,64010,ดารา,21.000,หญิง,ศิลปศาสตร์,3.560000,167.0,60.0,28.0,2024-01-03
10,64011,ธีระ,20.875,NaN,NaN,3.780000,NaN,68.0,NaN,2024-01-07
11,64012,นภา,22.000,ชาย,วิทยาศาสตร์,3.246111,171.0,NaN,16.0,2023-12-26
12,64013,บุญมี,20.000,หญิง,วิศวกรรมศาสตร์,3.230000,169.0,72.0,24.0,2023-12-26
13,64014,ปรีชา,21.000,ชาย,ศิลปศาสตร์,3.450000,164.0,54.0,19.0,2024-01-08
14,64015,พิมพ์,22.000,หญิง,วิทยาศาสตร์,3.670000,162.0,56.0,26.0,2024-02-06
15,64016,ภูมิ,19.000,ชาย,วิทยาศาสตร์,3.890000,173.0,78.0,14.0,2024-01-20
16,64017,มานี,20.000,หญิง,วิศวกรรมศาสตร์,3.010000,166.0,62.0,21.0,2024-01-24
17,64018,ยุพา,21.000,หญิง,NaN,3.230000,161.0,50.0,27.0,2024-01-08
18,64019,รัตนา,20.875,ชาย,ศิลปศาสตร์,3.246111,174.0,76.0,NaN,2023-12-18
19,64020,ลัดดา,22.000,NaN,วิทยาศาสตร์,3.450000,168.0,64.0,23.0,2024-01-06

In [65]:
maxhours = new_data['ชั่วโมงเรียน_ต่อสัปดาห์'].max()
minhours = new_data['ชั่วโมงเรียน_ต่อสัปดาห์'].min()
print(f"ชั่วโมงเรียน_ต่อสัปดาห์: สูงสุด = {maxhours}, ต่ำสุด = {minhours}")
meanHR = new_data['ชั่วโมงเรียน_ต่อสัปดาห์'].mean()

ชั่วโมงเรียน_ต่อสัปดาห์: สูงสุด = 35.0, ต่ำสุด = 10.0

In [66]:
new_data['ชั่วโมงเรียน_ต่อสัปดาห์'].fillna(meanHR, inplace=True)
new_data

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.000,ชาย,วิทยาศาสตร์,3.210000,170.0,65.0,15.000000,2024-01-23
1,64002,สมหญิง,21.000,หญิง,วิทยาศาสตร์,3.450000,165.0,58.0,20.000000,2024-02-05
2,64003,ไม่ระบุ,20.875,ชาย,วิทยาศาสตร์,3.670000,175.0,NaN,25.000000,2024-01-13
3,64004,สมศักดิ์,22.000,ชาย,วิทยาศาสตร์,3.246111,168.0,70.0,10.000000,2023-12-30
4,64005,สมใจ,19.000,หญิง,วิศวกรรมศาสตร์,3.890000,160.0,52.0,30.000000,2024-01-27
5,64006,กานต์,20.875,ชาย,วิศวกรรมศาสตร์,3.120000,172.0,75.0,12.000000,2023-12-23
6,64007,กิตติ,21.000,หญิง,วิศวกรรมศาสตร์,4.000000,158.0,48.0,35.000000,2024-01-05
7,64008,จิรา,20.000,หญิง,ศิลปศาสตร์,2.980000,180.0,82.0,18.000000,2024-01-23
8,64009,ชนาธิป,23.000,ชาย,ศิลปศาสตร์,3.340000,163.0,55.0,22.000000,2024-02-11
9,64010,ดารา,21.000,หญิง,ศิลปศาสตร์,3.560000,167.0,60.0,28.000000,2024-01-03
10,64011,ธีระ,20.875,NaN,NaN,3.780000,NaN,68.0,21.388889,2024-01-07
11,64012,นภา,22.000,ชาย,วิทยาศาสตร์,3.246111,171.0,NaN,16.000000,2023-12-26
12,64013,บุญมี,20.000,หญิง,วิศวกรรมศาสตร์,3.230000,169.0,72.0,24.000000,2023-12-26
13,64014,ปรีชา,21.000,ชาย,ศิลปศาสตร์,3.450000,164.0,54.0,19.000000,2024-01-08
14,64015,พิมพ์,22.000,หญิง,วิทยาศาสตร์,3.670000,162.0,56.0,26.000000,2024-02-06
15,64016,ภูมิ,19.000,ชาย,วิทยาศาสตร์,3.890000,173.0,78.0,14.000000,2024-01-20
16,64017,มานี,20.000,หญิง,วิศวกรรมศาสตร์,3.010000,166.0,62.0,21.000000,2024-01-24
17,64018,ยุพา,21.000,หญิง,NaN,3.230000,161.0,50.0,27.000000,2024-01-08
18,64019,รัตนา,20.875,ชาย,ศิลปศาสตร์,3.246111,174.0,76.0,21.388889,2023-12-18
19,64020,ลัดดา,22.000,NaN,วิทยาศาสตร์,3.450000,168.0,64.0,23.000000,2024-01-06

In [67]:
new_data['BMI'] = new_data['น้ำหนัก_kg'] / (new_data['ส่วนสูง_cm']/100)**2
new_data['สุขภาพ'] = pd.cut(new_data['BMI'],
                                   bins=[0, 18.5, 25, 30, 100],
                                   labels=['ผอม', 'ปกติ', 'อ้วน', 'อ้วนมาก'])

print(new_data[['ชื่อ', 'BMI', 'สุขภาพ']])

        ชื่อ        BMI สุขภาพ
0      สมชาย  22.491349   ปกติ
1     สมหญิง  21.303949   ปกติ
2    ไม่ระบุ        NaN    NaN
3   สมศักดิ์  24.801587   ปกติ
4       สมใจ  20.312500   ปกติ
5      กานต์  25.351541   อ้วน
6      กิตติ  19.227688   ปกติ
7       จิรา  25.308642   อ้วน
8     ชนาธิป  20.700817   ปกติ
9       ดารา  21.513859   ปกติ
10      ธีระ        NaN    NaN
11       นภา        NaN    NaN
12     บุญมี  25.209201   อ้วน
13     ปรีชา  20.077335   ปกติ
14     พิมพ์  21.338211   ปกติ
15      ภูมิ  26.061679   อ้วน
16      มานี  22.499637   ปกติ
17      ยุพา  19.289379   ปกติ
18     รัตนา  25.102391   อ้วน
19     ลัดดา  22.675737   ปกติ

In [68]:
Reg = new_data.copy()

In [69]:
Reg['วันที่ลงทะเบียน'] = pd.to_datetime(Reg['วันที่ลงทะเบียน'])

In [70]:
count_reg = Reg.groupby(Reg['วันที่ลงทะเบียน'].dt.date).size().reset_index(name='จำนวนนศ')

print("แต่ละวันที่นักศึกษาได้ลงทะเบียนเรียน")
print(count_reg)

แต่ละวันที่นักศึกษาได้ลงทะเบียนเรียน
   วันที่ลงทะเบียน  จำนวนนศ
0       2023-12-18        1
1       2023-12-23        1
2       2023-12-26        2
3       2023-12-30        1
4       2024-01-03        1
5       2024-01-05        1
6       2024-01-06        1
7       2024-01-07        1
8       2024-01-08        2
9       2024-01-13        1
10      2024-01-20        1
11      2024-01-23        2
12      2024-01-24        1
13      2024-01-27        1
14      2024-02-05        1
15      2024-02-06        1
16      2024-02-11        1